### ISSUE TITLE
Error: Invalid RSS Feed

### ISSUE THREAD

**Issue by sbrl** [pvigier/pvigier.github.io#1]
Hey!

I just discovered your blog [through Reddit](https://www.reddit.com/r/proceduralgeneration/comments/bnpexi/map_generation_in_vagabond/), and I'd like to subscribe to your blog via RSS.

Unfortunately, I discovered that your RSS feed is invalid:

![Selection_152](https://user-images.githubusercontent.com/9929737/57586938-19ca2b00-74f5-11e9-90a6-58425e7f3040.png)

I think its a case of using numeric escape codes (e.g. `&#1234;`) instead of the textual ones (e.g. `&abcd;`), as an Atom feed is XML.

_(Also, you need a `<link href="https://pvigier.github.io/rss.xml" rel="alternate" title="INSERT ATOM FEED TITLE" type="application/atom+xml" />` in the head of every page so that your feed is discoverable)_

**Comment by pvigier** [comment]
Thanks for reporting the issue and the advice!

I have fixed all of that normally.

Best

**Comment by sbrl** [comment]
Yay, thanks :D
